// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_LAbj0kicwTDa9d3bki_rktFVlmEVHxs',
    appId: '1:508514053433:web:766a44ed15aadcd335cce8',
    messagingSenderId: '508514053433',
    projectId: 'farmodo-34c9c',
    authDomain: 'farmodo-34c9c.firebaseapp.com',
    storageBucket: 'farmodo-34c9c.firebasestorage.app',
    measurementId: 'G-VVN8LLKH0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcXvGbY0qZksMDNGziLTDhBXrNtHuqPs',
    appId: '1:508514053433:android:3d4fe1dc8e1e0d5035cce8',
    messagingSenderId: '508514053433',
    projectId: 'farmodo-34c9c',
    storageBucket: 'farmodo-34c9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4JwBorFDYvL-audEn6jd6QYT6aqR0_pY',
    appId: '1:508514053433:ios:604e8478a9a3ccc235cce8',
    messagingSenderId: '508514053433',
    projectId: 'farmodo-34c9c',
    storageBucket: 'farmodo-34c9c.firebasestorage.app',
    iosBundleId: 'com.bilalcavus.farmodo',
  );
}
